name: motivation_alarm
description: motivation just do it
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  flutter_native_splash: ^2.3.2
  easy_localization: ^3.0.2
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  alarm: ^1.2.2
  animated_theme_switcher: ^2.0.8
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0

dependency_overrides:
  font_awesome_flutter:
    path: font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/translations/en-US.json
    - assets/translations/ru-RU.json
    - assets/music/alarm.mp3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/icon/icon.png"
