name: motivation_alarm
description: motivation just do it
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  dynamic_color: ^1.6.6
  easy_localization: ^3.0.2
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/translations/en-US.json
